### PR TITLE
Issue 490 support postgres

### PR DESCRIPTION
**Pull request by vnaz**

### CODE REVIEW

**Comment by vnaz** [comment]
go test github.com/ottemo/commerce/db/postgres

to check the base taste

**Comment by vastbinderj** [comment]
@vnaz  - this is just preliminary as you have conflicts to resolve, right?

**Comment by vastbinderj** [comment]
or did you want me to take a look at your tests?

**Comment by vastbinderj** [comment]
@vnaz can you post a working config, I guess I can figure it out in the module bootstrap code... but in case I am not successful...

Also, did you fix ottemo/commerce#504?

**Review by vastbinderj — CHANGES_REQUESTED** [review]
@vnaz - 2 big things and a few others:

1. add `github.com/lib/pq` to the dep .toml file
2. please fix the merge conflicts
3. can you include some basic settings for configuring postgres in the ottemo.ini?
4. when I run `go test github.com/ottemo/db/postgres` it seems to be doing something, but I don't see a log created and the process looks like it is trying to do something... I just can't tell what.

**Review by vastbinderj — APPROVED** [review]

**Pull request merged**
